require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
