name: RSpec

on:
  push:
    branches:
      - main

  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  rspec:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      GEMFILE_RUBY_VERSION: 3.3.4

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Main specs
        run: bundle exec rspec
